name: E2E Tests (Real API)

# Only run manually or on release
on:
  workflow_dispatch:  # Manual trigger
  release:
    types: [published]

jobs:
  e2e-tests:
    name: E2E Tests with Real API
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install -e ".[dev]"

    - name: Create .env file with secret
      run: |
        echo "REE_API_TOKEN=${{ secrets.REE_API_TOKEN }}" > .env

    - name: Run E2E tests
      run: |
        source .venv/bin/activate
        pytest tests/e2e/ -v --tb=short
      env:
        REE_API_TOKEN: ${{ secrets.REE_API_TOKEN }}

    - name: Clean up .env
      if: always()
      run: rm -f .env
